### ISSUE TITLE
soop_trv map and data stalled on db.

### ISSUE THREAD

**Issue by julian1** [aodn/geoserver-config#126]
@lbesnard 

This was working before, so maybe an issue with the harvester or the db

Also locks wms 1.1.1 getCapabilities on my test geoserver.

There were also a bunch of stalled queries on db for 4 - 10 hours

 10:39:42 |   11809 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 10:38:52 |   12201 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 10:34:42 |   12184 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 10:34:37 |   10784 | geoserver_123_12 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 10:33:52 |    5460 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 10:33:47 |   11544 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 10:29:37 |   11285 | geoserver_123_12 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 10:28:47 |   11810 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 08:41:16 |   10781 | geoserver_123_12 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 08:40:26 |   31052 | geoserver_123_12 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 08:36:16 |   13739 | geoserver_123_12 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 08:35:45 |   12410 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 08:35:26 |   12412 | geoserver_123_12 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 08:34:55 |   26226 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 08:30:45 |    9530 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 08:29:55 |   12797 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 06:53:07 |    2466 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 06:52:17 |    3551 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 06:48:07 |   32557 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 06:47:17 |   16114 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 06:21:34 |   11564 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 06:20:43 |    3550 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 06:16:33 |   19849 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 06:15:43 |   21818 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 04:57:01 |   26810 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 04:56:11 |   27696 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 04:52:01 |   18118 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 04:51:10 |    2940 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limited_
 04:37:46 |   14089 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_data" LIMIT 1000000) gt_limited_
 04:36:56 |   27695 | geoserver_123_11 | harvest  | SELECT count(*) AS gt_result_ FROM (SELECT * FROM "soop_trv"."soop_trv_trajectory_map" LIMIT 1000000) gt_limit

**Comment by xhoenner** [comment]
No error on Nagios so I assume it's okay.
