### ISSUE TITLE
Geoserver developments to improve visualisation

### ISSUE THREAD

**Issue by xhoenner** [aodn/geoserver-config#195]
Here we will list the Geoserver features that are not yet available but that would be valuable to improve the way we display data collections on Step 2 of the IMOS portal.

<h3>1. Specify the number of features for a WMS layer<h3>

In some cases we would like to limit the number of WMS features that get displayed on the portal. 

<i>Use case: SOOP TMV<i>

The Spirit of Tasmania cruises daily between Melbourne and Devonport, transmitting temperature, salinity, fluorescence and turbidity data in real-time. As the ship’s trajectory is always the same, we would like to represent only the latest ship track (Figure 1). 

![limit_wms_features](https://cloud.githubusercontent.com/assets/3443821/3696538/6129440c-1390-11e4-86c1-266bfa4d18a0.jpg)
Figure 1: A – ship tracks as displayed currently, B – latest ship track, we would like Geoserver to be able to get the latest track as users filter the WMS layer.

Currently the only way to do that is to create a table/view for the WMS layer with a single row for the latest ship track. This configuration is nonetheless problematic if users want to filter this layer. For instance if the latest ship track was done on the 27/01/2014 and they request data before this date, an empty layer would be returned. It therefore forces us to have all the data we want to display in the WMS layer.

<i>Proposed solutions:<i>
- Add a functionality in the layer configuration page asking how many features we want the WMS layer to return.
- Configure the Geoserver style so that it would always only display the feature associated with the latest date.

<h3>2. Use of a colour gradient in Geoserver style<h3>

Geoserver styles allow users to colour-code the data they want to display according to their values.

<i>Use case: temperature layer<i>

We would like to visualise temperature data recorded by several platforms (e.g. ships of opportunity, Argo floats, seals and sea lions) in a single layer. In the Geoserver style, we want to specify that the colour at each measurement’s location is determined by the temperature recorded at the measurement’s location (Figure 2). At the moment, we have to specify manually the colour for each temperature range (e.g. below 0 degrees → dark blue, between 0 and 5 degrees → blue), which isn’t practical.

![image](https://cloud.githubusercontent.com/assets/3443821/3696715/94ba221a-1394-11e4-9eb0-c574949319e9.png)

Figure 2: Screenshot of the portal showing the temperature at each measurement’s location.

We would like Geoserver to build a temperature range based on the content of the layer and colour-code it automatically. Phil told me he had a PHP script to do that in the AUV viewer but it has been abandoned recently, maybe it can be restored?

**Comment by pblain** [comment]
Added to backlog
