### ISSUE TITLE
geoserver prod master branch - diverge

### ISSUE THREAD

**Issue by lbesnard** [aodn/geoserver-config#254]
Looking at https://github.com/aodn/geoserver-config/network
it seems like the prod and master branch diverge quite a bit, or actually quite a lot (since early january)! I have the feeling many commits are missing in the prod branch ...

would be good to investigate

**Comment by ggalibert** [comment]
My fault. My last attempt to merge failed due to conflicts on

workspaces/imos/JNDI_argo/argo_profile_data/filters.xml

I'll try to fix that.

**Comment by ggalibert** [comment]
Sorted.

workspaces/imos/JNDI_argo/argo_profile_data/filters.xml didn't appear to have just been renamed. Its content had slighly changed too! (a label updated with one upper case)
