### ISSUE TITLE
auv track disappear at random zoom level 

### ISSUE THREAD

**Issue by lbesnard** [aodn/geoserver-config#273]
The viewer has been having some issues displaying tracks lately. I tried to see where the reason can come from. I ended up finding a possible issue:

This example doesn't display anything (on chrome ingnito, so no cache issue)
http://geoserver-123.aodn.org.au/geoserver/imos/wms?service=WMS&version=1.1.0&request=GetMap&layers=imos:auv_tracks_vw&styles=&bbox=114.9608,-30.2384,114.9609,-30.238&width=1228&height=512&srs=EPSG:4326&format=application/openlayers

Adding a random value of buffer = 5000 (see end of url), the track is displayed
http://geoserver-123.aodn.org.au/geoserver/imos/wms?service=WMS&version=1.1.0&request=GetMap&layers=imos:auv_tracks_vw&styles=&bbox=114.9608,-30.2384,114.9609,-30.238&width=1228&height=512&srs=EPSG:4326&format=application/openlayers&buffer=5000

Curling it shows
```
      var untiled = new ol.layer.Image({
        source: new ol.source.ImageWMS({
          ratio: 1,
          url: 'http://geoserver-123.aodn.org.au/geoserver/imos/wms',
          params: {'FORMAT': format,
                   'VERSION': '1.1.1',  
                BUFFER: '5000',
                LAYERS: 'imos:auv_tracks_vw',
                STYLES: '',
          }
        })
      });
```

@danfruehauf , any idea why this is not behaving the way it should
@pmbohm FYI

__UPDATE__ the buffer value makes it work from value = 280 onwards

**Comment by lbesnard** [comment]
@jkburges  FYI

**Comment by xhoenner** [comment]
@danfruehauf did you have a look at that bug?

**Comment by danfruehauf** [comment]
I haven't at all, no...

**Comment by dnahodil** [comment]
Basically it seems that the track will not be rendered if the start point is not going to be on the tile. This can be easily seen at the zoom levels where a green and red point show the start and end of the track, respectively.

**Comment by dnahodil** [comment]
@lbesnard (the fixer[!](http://edge.alluremedia.com.au/uploads/businessinsider/2015/03/pyne-gif.gif)) and I have tried converting the current geometry, which is represented as a linestring, into a multilinestring. This seems to have fixed the problem and continues to work as expected in the AUV Viewer.

**Comment by xhoenner** [comment]
That seems to be fixed, @lbesnard close?
