### ISSUE TITLE
nsw_oeh_bathy.sld not showing at all zoom levels

### ISSUE THREAD

**Issue by pmbohm** [aodn/geoserver-config#425]
When zoomed out there is no drawing of the features. 

![screen shot 2016-12-14 at 1 23 27 pm](https://cloud.githubusercontent.com/assets/1066981/21167434/89d13704-c200-11e6-93eb-a84c4ecaa4df.png)

![screen shot 2016-12-14 at 1 24 40 pm](https://cloud.githubusercontent.com/assets/1066981/21167456/b2fcb7fc-c200-11e6-813e-02173ef1e0c5.png)

**Comment by mhidas** [comment]
I think this can be closed... seems ok now: https://portal.aodn.org.au/search?uuid=60160b01-8ffc-45ce-a6f4-ee70ce391ec6
Maybe this was just a caching issue?

**Comment by mhidas** [comment]
@pmbohm ??
