### ISSUE TITLE
anmn_ctd_profile_data is missing CPHL column

### ISSUE THREAD

**Issue by ggalibert** [aodn/geoserver-config#426]
In this collection Chlorophyll data can be found under a parameter code CPHL. This needs to be added to the wfs layer.

**Comment by ggalibert** [comment]
This https://github.com/aodn/harvesters/issues/491 needs to be fixed first.

**Comment by mhidas** [comment]
I don't think anything actually needs changing in the geoserver config, unless you want to filter on the new column. It might need a geoserver restart / config reload to pick up the change in the db table.

**Comment by mhidas** [comment]
Closing as this is reported in https://github.com/aodn/content/issues/209
