### ISSUE TITLE
Production Master -> out of sync

### ISSUE THREAD

**Issue by lbesnard** [aodn/geoserver-config#493]
Both branches are completely out of sync
```This branch is 8 commits ahead, 64 commits behind master.```

I think It becomes important to clean that up

@aodn/emii-data-team

**Comment by ggalibert** [comment]
Can you please list those commits and their owner?

**Comment by lwgordonimos** [comment]
https://github.com/aodn/geoserver-config/compare/production...master

**Comment by lwgordonimos** [comment]
The initial reason for cherry-picking vs merging was because the Deakin bathy changes not ready for production yet, but were almost ready. If we revert those, we could in theory run the merge (if not other problematic commits not yet ready for production).

**Comment by ggalibert** [comment]
I don't see why we couldn't push the Deakin bathy stuff to prod. It has been tested and works in master. + The metadata record is not on prod yet so the layer won't be visible / accessible anyway yet.

**Comment by mhidas** [comment]
:+1: My commits are ok to merge to prod.

**Comment by smancini** [comment]
I have tested again the Deakin bathy in RC and it works well.
So I think we can merge the Deakin bathy changes into production.

**Comment by xhoenner** [comment]
All my commits can be merged to prod except those related to aus_chla_db and aatams_acoustic

**Comment by mhidas** [comment]
Ok, we're back to production == master!
Thanks @lwgordonimos
