### ISSUE TITLE
Bad data point from ANMN dataset (anmn_velocity_timeseries_map)

### ISSUE THREAD

**Issue by pmbohm** [aodn/geoserver-config#87]
Bad data point a few hundred Km's inside South Africa
for IMOS - Australian National Mooring Network (ANMN) Facility - Current velocity time-series (anmn_velocity_timeseries_map)

![screenshot from 2014-01-22 15 58 46](https://f.cloud.github.com/assets/1066981/1971170/ecc82e9c-8321-11e3-856b-582fb04c10e5.png)

**Comment by xhoenner** [comment]
This seems to be fixed
